name: Deploy to Vimexx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Vimexx
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: web0107.zxcs.nl
        username: u54933p52213
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /path/to/your/website
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
